
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA DOLAR ELEMENT ELEMENTS ENTERO ID IGUAL ITEM LQUESTION RQUESTION TYPEinit : LQUESTION ELEMENTS RQUESTION elementos LQUESTION DOLAR ELEMENTS RQUESTIONelementos : elementos elementoelementos : elementoelemento : LQUESTION ELEMENT TYPE IGUAL CADENA RQUESTION datos LQUESTION DOLAR ELEMENT RQUESTIONdatos : datos datodatos : datodato : LQUESTION ITEM ID IGUAL CADENA DOLAR RQUESTION\n            | LQUESTION ITEM ID IGUAL ENTERO DOLAR RQUESTION'
    
_lr_action_items = {'LQUESTION':([0,4,6,7,10,17,19,20,23,30,33,34,],[2,5,9,-3,-2,18,22,-6,-5,-4,-7,-8,]),'$end':([1,16,],[0,-1,]),'ELEMENTS':([2,12,],[3,14,]),'RQUESTION':([3,14,15,27,31,32,],[4,16,17,30,33,34,]),'ELEMENT':([5,9,25,],[8,8,27,]),'TYPE':([8,],[11,]),'DOLAR':([9,22,28,29,],[12,25,31,32,]),'IGUAL':([11,24,],[13,26,]),'CADENA':([13,26,],[15,28,]),'ITEM':([18,22,],[21,21,]),'ID':([21,],[24,]),'ENTERO':([26,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'elementos':([4,],[6,]),'elemento':([4,6,],[7,10,]),'datos':([17,],[19,]),'dato':([17,19,],[20,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> LQUESTION ELEMENTS RQUESTION elementos LQUESTION DOLAR ELEMENTS RQUESTION','init',8,'p_init','parser.py',7),
  ('elementos -> elementos elemento','elementos',2,'p_elementos_lista','parser.py',10),
  ('elementos -> elemento','elementos',1,'p_elementos_elemento','parser.py',13),
  ('elemento -> LQUESTION ELEMENT TYPE IGUAL CADENA RQUESTION datos LQUESTION DOLAR ELEMENT RQUESTION','elemento',11,'p_elemento','parser.py',16),
  ('datos -> datos dato','datos',2,'p_datos','parser.py',19),
  ('datos -> dato','datos',1,'p_datos_dato','parser.py',23),
  ('dato -> LQUESTION ITEM ID IGUAL CADENA DOLAR RQUESTION','dato',7,'p_dato','parser.py',26),
  ('dato -> LQUESTION ITEM ID IGUAL ENTERO DOLAR RQUESTION','dato',7,'p_dato','parser.py',27),
]
